name: Build & Release


on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  build-version-number: 0.2.${{ github.run_number }}  
  docker-image-name: ghcr.io/tonycknight/tubescan:v0.2.${{ github.run_number }}
  
jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: "6.0.x"
        
      - name: dotnet SCA
        run: |
          dotnet tool restore
          dotnet restore
          dotnet list package --vulnerable --include-transitive | tee results.log

          FOUND_VULN=`grep -c 'has the following vulnerable packages' results.log` || true
          FOUND_CRIT=`grep -c 'Critical' results.log` || true
          FOUND_HIGH=`grep -c 'High' results.log` || true
          
          if [[ "$FOUND_VULN" != "0" ]]
          then
            if [ "$FOUND_CRIT" == "0" -a "$FOUND_HIGH" == "0"]
            then
              echo "### Vulnerable packages found ###"
              exit 0
            fi
            echo "### Critical/High vulnerable packages found ###"
            exit 1
          fi
          echo "## No problems found ##"
          exit 0

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: "6.0.x"
        
      - name: dotnet tool restore
        run: dotnet tool restore
              
      - name: Run build
        run: dotnet fake run "build.fsx" -t "All"

      - name: Archive Test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tests.results
          path: |
            ./tests/**/TestResults/*
            
      - name: Archive Stryker results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: stryker.results
          path: |
            ./StrykerOutput/**

      - name: Archive Code coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: codecoverage
          path: ./publish/codecoverage/*.*
          
      - name: Unit test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: unit test results
          path: ${{ github.workspace }}/tests/TubeScan.Tests/TestResults/test_results.trx
          reporter: dotnet-trx
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Code coverage results
        uses: 5monkeys/cobertura-action@master
        if: always()
        with:
          path: ${{ github.workspace }}/tests/TubeScan.Tests/TestResults/coverage.info
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 70
          fail_below_threshold: false
          show_line: true
          show_branch: true
          show_missing: true
          show_class_names: true
          link_missing_lines: true
          report_name: code coverage results

  codeql:
    uses: ./.github/workflows/codeql-analysis.yml

  build-docker-image:
    runs-on: ubuntu-latest
    needs:   [ build, sca, codeql ]

    steps:
      - uses: actions/checkout@v2

      - name: Set Preview Docker image name
        run: |
          echo "docker-image-name=${{ env.docker-image-name }}-preview" >> $GITHUB_ENV
        if:${{ if: github.ref != 'refs/heads/main' }}

      - name: Build docker image
        run: docker build -t ${{ env.docker-image-name }} --build-arg BuildVersion=${{ env.build-version-number }} .

      - name: Login to GitHub Container Registry
        #if: github.ref == 'refs/heads/main'
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}

      - name: Push docker image
        #if: github.ref == 'refs/heads/main' 
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push ${{ env.docker-image-name }}

  create-gh-release:
    runs-on: ubuntu-latest
    needs: [ build-docker-image ]    
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:    
      - uses: actions/checkout@v2

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.build-version-number }}
          prerelease: true
          generateReleaseNotes: true

