name: "SCA"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      token:
        required: false
  schedule:
    - cron: '16 2 * * 4'

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore packages
        run: |
          dotnet tool restore
          dotnet restore

      - name: Run SCA
        uses: tonycknight/pkgchk-action@v1.0.12
        with:
          project-path: src/TubeScan/TubeScan.csproj
